### ISSUE TITLE
Ankerctl thrown an error on update

### ISSUE THREAD

**Issue by Phoenix-DH** [sondregronas/ankermake-hass-component#10]
Sorry that Inpost this issue from the addon here, but I cannot open an topic in the other branch.

I receive an error during update:
invalid tag 'cff83567/aarch64-addon-ankerctl:': invalid reference format

I habe according to the plugin version 1.2.3

**Comment by sondregronas** [comment]
Hi!

This was due to my auto-update script failing to get a version number so version was set to nil. This should no longer happen: https://github.com/sondregronas/ankermgmt-hassio-addons/commit/26bd073fbf4d2f7b6e71cd5ac670d7965230a817

Go to AddOns, press the "Check for Updates" button on the top right, and the "New update available" notification will disappear after a while / after a reboot.

**Comment by Phoenix-DH** [comment]
It has gone 👍🏻 Thanks
